import 'package:flutter/material.dart';

const apiUrl = 'https://api.coincap.io/v2/assets';
const iconApiUrl = 'https://coinicons-api.vercel.app/api/icon';
const jsBachUrl =
    'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Johann_Sebastian_Bach.jpg/440px-Johann_Sebastian_Bach.jpg';
const usdApiUrl = "https://api.genelpara.com/embed/doviz.json";

const symbols = [
  "BTC",
  "ETH",
  "USDT",
  "BNB",
  "USDC",
  "XRP",
  "SOL",
  "ADA",
  "DOGE",
  "TRX",
  "DAI",
  "DOT",
  "MATIC",
  "LTC",
  "WBTC",
  "BCH",
  "SHIB",
  "LINK",
  "LEO",
  "AVAX",
  "TUSD",
  "XLM",
  "XMR",
  "OKB",
  "UNI",
  "BUSD",
  "ETC",
  "ATOM",
  "BTCB",
  "FIL",
  "LDO",
  "MKR",
  "ICP",
  "CRO",
  "VET",
  "QNT",
  "NEAR",
  "AAVE",
  "ALGO",
  "GRT",
  "STX",
  "HBAR",
  "XTZ",
  "RNDR",
  "BSV",
  "AXS",
  "EOS",
  "SAND",
  "THETA",
  "XDC",
  "RUNE",
  "EGLD",
  "INJ",
  "MANA",
  "FTM",
  "KAVA",
  "USDP",
  "NEO",
  "XEC",
  "SNX",
  "FLOW",
  "ZEC",
  "KCS",
  "CHZ",
  "FEI",
  "IOTA",
  "TWT",
  "OCEAN",
  "CFX",
  "FXS",
  "RPL",
  "CRV",
  "KLAY",
  "HT",
  "DYDX",
  "MINA",
  "CSPR",
  "GT",
  "FTT",
  "GALA",
  "COMP",
  "DASH",
  "WOO",
  "NEXO",
  "ZIL",
  "ROSE",
  "AR",
  "BAT",
  "CAKE",
  "1INCH",
  "GNO",
  "LOOM",
  "LRC",
  "XEM",
  "QTUM",
  "CVX",
  "ELF",
  "ENJ",
  "CELO",
  "MASK"
];
const ids = [
  "bitcoin",
  "ethereum",
  "tether",
  "binance-coin",
  "usd-coin",
  "xrp",
  "solana",
  "cardano",
  "dogecoin",
  "tron",
  "multi-collateral-dai",
  "polkadot",
  "polygon",
  "litecoin",
  "wrapped-bitcoin",
  "bitcoin-cash",
  "shiba-inu",
  "chainlink",
  "unus-sed-leo",
  "trueusd",
  "avalanche",
  "stellar",
  "monero",
  "okb",
  "uniswap",
  "binance-usd",
  "ethereum-classic",
  "cosmos",
  "bitcoin-bep2",
  "filecoin",
  "lido-dao",
  "maker",
  "internet-computer",
  "crypto-com-coin",
  "vechain",
  "quant",
  "near-protocol",
  "aave",
  "algorand",
  "the-graph",
  "stacks",
  "hedera-hashgraph",
  "render-token",
  "tezos",
  "bitcoin-sv",
  "axie-infinity",
  "eos",
  "theta",
  "the-sandbox",
  "thorchain",
  "elrond-egld",
  "injective-protocol",
  "xinfin-network",
  "decentraland",
  "fantom",
  "kava",
  "paxos-standard",
  "neo",
  "ecash",
  "fei-protocol",
  "synthetix-network-token",
  "flow",
  "zcash",
  "kucoin-token",
  "chiliz",
  "iota",
  "trust-wallet-token",
  "ocean-protocol",
  "frax-share",
  "conflux-network",
  "curve-dao-token",
  "rocket-pool",
  "klaytn",
  "huobi-token",
  "mina",
  "dydx",
  "casper",
  "gatetoken",
  "ftx-token",
  "gala",
  "compound",
  "dash",
  "wootrade",
  "nexo",
  "zilliqa",
  "oasis-network",
  "arweave",
  "basic-attention-token",
  "pancakeswap",
  "1inch",
  "gnosis-gno",
  "loom-network",
  "nem",
  "loopring",
  "qtum",
  "aelf",
  "enjin-coin",
  "celo",
  "mask-network",
  "singularitynet"
];

const List<List<Color>> palette = [
  [
    Color.fromARGB(255, 120, 20, 108),
    Color.fromARGB(255, 148, 42, 136),
    Color.fromARGB(255, 175, 64, 163),
    Color.fromARGB(255, 230, 107, 217),
  ],
  [
    Color.fromARGB(255, 225, 215, 77),
    Color.fromARGB(255, 214, 187, 47),
    Color.fromARGB(255, 209, 173, 32),
    Color.fromARGB(255, 203, 159, 17),
  ],
  [
    Color.fromARGB(255, 103, 186, 82),
    Color.fromARGB(255, 95, 198, 49),
    Color.fromARGB(255, 91, 204, 33),
    Color.fromARGB(255, 87, 209, 16),
  ],
  [
    Color.fromARGB(255, 99, 185, 196),
    Color.fromARGB(255, 56, 179, 195),
    Color.fromARGB(255, 34, 176, 195),
    Color.fromARGB(255, 12, 173, 194),
  ],
];
